classdef problem_cluster_gnn_v3 < UserProblem
    methods
        function obj = problem_cluster_gnn_v3(varargin)
            projectRoot = pack_project_root();
            up = readNPY(fullfile(projectRoot, 'clustering', 'community_output', 'community_total_area.npy'));
            up = double(up(:))';
            upper = reshape(repmat(up, 3, 1), 1, []);
            constraints = arrayfun( ...
                @(i)sprintf('x(%d)+x(%d)+x(%d)-%.12g', 3*i, 3*i-1, 3*i-2, up(i)), ...
                1:length(up), ...
                'UniformOutput', false);
            obj = obj@UserProblem(varargin{:}, ...
                'encoding', ones(1, length(up) * 3), ...
                'lower', zeros(1, length(up) * 3), ...
                'upper', upper, ...
                'data', '', ...
                'initFcn', '', ...
                'decFcn', '', ...
                'objFcn', {@(x)lid_gnn_v3_objective(x), @(x)construction_cost(x)}, ...
                'conFcn', constraints);
        end
    end
end
